### ISSUE TITLE
这个项目还维护吗? 

### ISSUE THREAD

**Issue by Seraphli** [zjinh/electron-vue-cli3#4]
npm install提示了很多warn
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile fork-ts-checker-webpack-plugin-v5: No matching version found for fork-ts-checker-webpack-plugin-v5@5.2.1.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9)
npm WARN old lockfile  Could not fetch metadata for fork-ts-checker-webpack-plugin-v5@5.2.1 fork-ts-checker-webpack-plugin-v5: No matching version found for fork-ts-checker-webpack-plugin-v5@5.2.1.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '5.2.1',
npm WARN old lockfile   versions: [ '0.0.1-security' ],
npm WARN old lockfile   distTags: { latest: '0.0.1-security' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile vue-loader-v16: No matching version found for vue-loader-v16@16.5.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9)
npm WARN old lockfile  Could not fetch metadata for vue-loader-v16@16.5.0 vue-loader-v16: No matching version found for vue-loader-v16@16.5.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '16.5.0',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '16.0.0-beta.5.4',
npm WARN old lockfile     '16.0.0-beta.5.3',
npm WARN old lockfile     '16.0.0-beta.5.2',
npm WARN old lockfile     '16.0.0-beta.5.1',
npm WARN old lockfile     '16.0.0-beta.5'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '16.0.0-beta.5.4' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

**Comment by zjinh** [comment]
最新版的应该没问题吧，之前更新了ts的版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/electron-vue-cli3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 中午12:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zjinh/electron-vue-cli3] 这个项目还维护吗?  (Issue #4)





 
npm install提示了很多warn
 npm WARN old lockfile  npm WARN old lockfile The package-lock.json file was created with an old version of npm, npm WARN old lockfile so supplemental metadata must be fetched from the registry. npm WARN old lockfile  npm WARN old lockfile This is a one-time fix-up, please be patient... npm WARN old lockfile  npm WARN old lockfile fork-ts-checker-webpack-plugin-v5: No matching version found for ***@***.*** npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23) npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26 npm WARN old lockfile     at async Array.<anonymous&gt; ***@***.***/arborist/lib/arborist/build-ideal-tree.js:741:9) npm WARN old lockfile  Could not fetch metadata for ***@***.*** fork-ts-checker-webpack-plugin-v5: No matching version found for ***@***.*** npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23) npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26 npm WARN old lockfile     at async Array.<anonymous&gt; ***@***.***/arborist/lib/arborist/build-ideal-tree.js:741:9) { npm WARN old lockfile   code: 'ETARGET', npm WARN old lockfile   type: 'version', npm WARN old lockfile   wanted: '5.2.1', npm WARN old lockfile   versions: [ '0.0.1-security' ], npm WARN old lockfile   distTags: { latest: '0.0.1-security' }, npm WARN old lockfile   defaultTag: 'latest' npm WARN old lockfile } npm WARN old lockfile vue-loader-v16: No matching version found for ***@***.*** npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23) npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26 npm WARN old lockfile     at async Array.<anonymous&gt; ***@***.***/arborist/lib/arborist/build-ideal-tree.js:741:9) npm WARN old lockfile  Could not fetch metadata for ***@***.*** vue-loader-v16: No matching version found for ***@***.*** npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23) npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26 npm WARN old lockfile     at async Array.<anonymous&gt; ***@***.***/arborist/lib/arborist/build-ideal-tree.js:741:9) { npm WARN old lockfile   code: 'ETARGET', npm WARN old lockfile   type: 'version', npm WARN old lockfile   wanted: '16.5.0', npm WARN old lockfile   versions: [ npm WARN old lockfile     '16.0.0-beta.5.4', npm WARN old lockfile     '16.0.0-beta.5.3', npm WARN old lockfile     '16.0.0-beta.5.2', npm WARN old lockfile     '16.0.0-beta.5.1', npm WARN old lockfile     '16.0.0-beta.5' npm WARN old lockfile   ], npm WARN old lockfile   distTags: { latest: '16.0.0-beta.5.4' }, npm WARN old lockfile   defaultTag: 'latest' npm WARN old lockfile } npm WARN deprecated ***@***.***: Please see https://github.com/lydell/urix#deprecated npm WARN deprecated ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details. npm WARN deprecated ***@***.***: https://github.com/lydell/resolve-url#deprecated npm WARN deprecated ***@***.***: The querystring API is considered Legacy. new code should use the URLSearchParams API instead. npm WARN deprecated ***@***.***: this package is now deprecated npm WARN deprecated ***@***.***: this library is no longer supported npm WARN deprecated ***@***.***: request has been deprecated, see https://github.com/request/request/issues/3142 npm WARN deprecated ***@***.***: 3.x is no longer supported npm WARN deprecated ***@***.***: This loader has been deprecated. Please use eslint-webpack-plugin npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained npm WARN deprecated @***@***.***: Moved to 'npm install @sideway/address' npm WARN deprecated ***@***.***: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies. npm WARN deprecated ***@***.***: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2. npm WARN deprecated ***@***.***: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies. npm WARN deprecated ***@***.***: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2. npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained npm WARN deprecated ***@***.***: This SVGO version is no longer supported. Upgrade to v2.x.x. npm WARN deprecated @***@***.***: Switch to 'npm install joi' npm WARN deprecated ***@***.***: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap. npm WARN deprecated ***@***.***: outdated version, please use @next npm WARN deprecated ***@***.***: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Seraphli** [comment]
这个就是刚刚安装时的提示, 后面还有错误, 看上去是node-gyp 16.13.0编译错误
```
.node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:665:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
```

**Comment by zjinh** [comment]
我windows、mac电脑都试了，是正常的。会不会是node环境问题呢，我的node版本是14.16.1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/electron-vue-cli3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 中午1:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjinh/electron-vue-cli3] 这个项目还维护吗?  (Issue #4)





 
这个就是刚刚安装时的提示, 后面还有错误, 看上去是node-gyp 16.13.0编译错误
 .node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'? npm ERR!             !std::is_same<Data, std::remove_cv_t<T&gt;&gt;::value&gt;::Perform(data); npm ERR!                                 ~~~~~^~~~~~~~~~~ npm ERR!                                      remove_cv npm ERR! /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:665:50: note: 'remove_cv' declared here npm ERR! template <class _Tp&gt; struct _LIBCPP_TEMPLATE_VIS remove_cv npm ERR!                                                  ^ npm ERR! 1 error generated.  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Seraphli** [comment]
哦我的是 v16.13.0, 可能是这个导致的

**Comment by zjinh** [comment]
嗯，有可能




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/electron-vue-cli3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjinh/electron-vue-cli3] 这个项目还维护吗?  (Issue #4)





 
哦我的是 v16.13.0, 可能是这个导致的
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Seraphli** [comment]
确实, 改用14就没问题了
